CONFIG_I2C=y
CONFIG_GPIO=y

CONFIG_TFM_SECURE_UART=n
CONFIG_TFM_LOG_LEVEL_SILENCE=y

# CONFIG_CONSOLE=y
# Replacing UART Console with RTT
CONFIG_UART_CONSOLE=n
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y

CONFIG_SHELL_BACKEND_RTT=y
CONFIG_SHELL_BACKEND_SERIAL=y

CONFIG_SHELL=y
CONFIG_I2C_SHELL=y